Create log file in standard location instead of working directory.
CasperWA/voila-optimade-client pull request #130
Opened 2020-09-04 14:00 UTC by csadorf

Needed to move `APP_AUTHOR` and `APP_NAME` constants into `version` module to avoid circular import.

2020-09-04 15:03 UTC, CasperWA requested changes
Thanks @csadorf !

I'd prefer not to introduce `version.py`, however. There are also other files (and `invoke` tasks) relying on `__version__` being in `__init__.py`.

2020-09-04 15:03 UTC, CasperWA commented on aiidalab_optimade/version.py
> +APP_NAME = "OPTIMADE"
I don't like creating this file, then I'd rather have these variables defined in `__init__.py`. It seems more "pythonic" keeping these in `__init__.py`.

2020-09-04 15:06 UTC, csadorf commented on aiidalab_optimade/version.py
> +APP_NAME = "OPTIMADE"
That is not possible, because it would lead to circular imports. See here for examples that this a standard approach:
- https://github.com/numpy/numpy/blob/c970c04cbeb38c80901a02bc573a9333458d4c4a/numpy/__init__.py#L134
- https://github.com/scipy/scipy/blob/fadab68044339b8d2fa194e1c71a907a6ecf0051/scipy/__init__.py#L127

2020-09-07 08:56 UTC, CasperWA approved these changes
Still not happy with the change in API that this PR introduces - however, to get the a new release in, I will merge this for now.

2020-09-07 08:56 UTC, merged

2020-09-07 08:57 UTC, csadorf commented
> Still not happy with the change in API that this PR introduces - however, to get the a new release in, I will merge this for now.

What change in API?

2020-09-07 08:58 UTC, CasperWA commented
> > Still not happy with the change in API that this PR introduces - however, to get the a new release in, I will merge this for now.
> 
> What change in API?

The Python API - the addition of `aiidalab_optimade.version`.

2020-09-07 09:02 UTC, csadorf commented
> > > Still not happy with the change in API that this PR introduces - however, to get the a new release in, I will merge this for now.
> > 
> > 
> > What change in API?
> 
> The Python API - the addition of `aiidalab_optimade.version`.

Sorry, I just deleted my comment to provide more context, before you already replied. I am extremely confused by your feedback here.

1. The API was extended by introducing another module, but none of the existing API was changed. That's technically a "change in API", but a very minor and backwards compatible one.
2. What exactly is the issue with this beyond your impression that it is not "pythonic"?
3. If you see a better way to avoid circular imports, I'm all for it. The only alternative I see is to not share constants and duplicate them in the various modules.

I am happy to discuss and implement an alternative solution, but I don't think it's fair to dismiss my contribution (following standard methods) without providing any real reason or alternative.

2020-09-07 09:12 UTC, CasperWA commented
> > > > Still not happy with the change in API that this PR introduces - however, to get the a new release in, I will merge this for now.
> > > 
> > > 
> > > What change in API?
> > 
> > 
> > The Python API - the addition of `aiidalab_optimade.version`.
> 
> Sorry, I just deleted my comment to provide more context, before you already replied. I am extremely confused by your feedback here.
> 
> 1. The API was extended by introducing another module, but none of the existing API was changed. That's technically a "change in API", but a very minor and backwards compatible one.
> 2. What exactly is the issue with this beyond your impression that it is not "pythonic"?
> 3. If you see a better way to avoid circular imports, I'm all for it. The only alternative I see is to not share constants and duplicate them in the various modules.
> 
> I am happy to discuss and implement an alternative solution, but I don't think it's fair to dismiss my contribution (following standard methods) without providing any real reason or alternative.

Sorry.
These PRs to the `aiidalab` branch are just messing with the current workflow of the repository. They should go through `develop` to `aiidalab` for now, and then after the split up they should go to the parent repository.
I will have to cherrypick stuff out to deal with this either this week or the week after to try and avoid messing up stuff for the review.
For now, I'll just make sure `aiidalab` can be deployed, and then these rushed changes can be addressed.

E.g., I would have like to use `setuptools` to retrieve the app name and author; keep it all defined just once.
Check if there is a need to include a new dependency or if we can get away betting on single OS support being fine (for this I think the solution you've come up with makes the most sense).
In the end, it feels like trying to decorate a room of a house in the middle of moving out - but if it's supposed to be used for the last day, then it's fine to set it up before moving (if that makes sense).

Upon the move I will keep the history and try to involve both you and @yakutovicha more in the development going forward. To the extent you intend to contribute.

Perhaps this doesn't relate directly to your questions, but I hope it explains my decisions here?

2020-09-07 09:28 UTC, csadorf commented
> Upon the move I will keep the history and try to involve both you and @yakutovicha more in the development going forward. To the extent you intend to contribute.
> 
👍 

> Perhaps this doesn't relate directly to your questions, but I hope it explains my decisions here?

Ok, I get it. Happy to help sorting things out next week.