Use ase format for viewer and default download format
CasperWA/voila-optimade-client pull request #432
Opened 2022-06-01 11:03 UTC by unkcpz

The structure adaptor of optimate-python-tooll now not properly deal
with the 2d structures in pdb and cif format which always purge cell.
This cause the issue that viewer will not shouw cell for two-dimensional
structures and the download format cif broken.
The ase format as adapter works fine, and it is also the adaptor in
aiidalab-base-widget and works all good there.

2022-06-07 12:43 UTC, CasperWA requested changes

2022-06-07 12:43 UTC, CasperWA commented on optimade_client/summary.py
> +        ),
This should be simply commented out as it can be confusing to have the same conversion option twice with a (for some users) cryptic difference of using ASE. But it's good to keep it in the code as a reference and information that it exists. So commenting these lines out should be good enough.
```suggestion
        # (
        #     "Crystallographic Information File v1.0 (.cif)",
        #     {"ext": ".cif", "adapter_format": "cif"},
        # ),
```

2022-06-07 12:43 UTC, CasperWA commented on optimade_client/summary.py
> +            nglview.ASEStructure(change["new"].convert('ase'))
Neat.

2022-06-07 12:44 UTC, CasperWA commented
Also, please run `pre-commit run --all-files` and commit and push the changes.
I can recommend to run `pre-commit install` in the root of the repository as well to have `pre-commit` run on every commit so you don't run into the `pre-commit` CI test failing again (or not as often 😉 )

2022-06-07 13:06 UTC, unkcpz commented
> Also, please run pre-commit run --all-files and commit and push the changes.
I can recommend to run pre-commit install in the root of the repository as well to have pre-commit run on every commit so you don't run into the pre-commit CI test failing again (or not as often 😉 )

Indeed! Always forget `pre-commit install` for a newly cloned repo. Will do.

2022-06-08 09:27 UTC, unkcpz commented
Hi @CasperWA, I see you just push commits, so I'll just let you do finalize this. Thanks!

2022-06-08 13:00 UTC, CasperWA approved these changes

2022-06-08 13:01 UTC, merged