Move default database providers defaults setup parameters to one file
CasperWA/voila-optimade-client pull request #449
Opened 2022-07-11 16:41 UTC by unkcpz

2022-07-11 16:42 UTC, unkcpz commented
Has been tested locally.

2022-08-16 09:01 UTC, CasperWA requested changes
No need to create a whole submodule with an `__init__.py` file for the parameters, Feel free to simply create a root `config_parameters.py`, `config_defaults.py`, `defaults.py`, `default_parameters.py` or similar file in which to put the defaults.

Please note in the eventual commit message that you're changing the defaults as well (for the `PROVIDER_DATABASE_GROUPINGS` at least.

2022-08-17 21:18 UTC, unkcpz commented
@CasperWA Thanks! I also add a change to put some providers on to skip list. 

> Please note in the eventual commit message that you're changing the defaults as well (for the PROVIDER_DATABASE_GROUPINGS at least.

Sure! will do it.

2022-09-19 11:33 UTC, unkcpz commented
Hi @CasperWA, I think this is ready for another round of review. Could you have a look?

2022-09-19 11:51 UTC, CasperWA requested changes

2022-09-19 11:51 UTC, CasperWA commented on optimade_client/default_parameters.py
> +# it but has issue to serve the data.
These sentences are very difficult to parse for me, could you please update them?

2022-09-19 11:51 UTC, CasperWA commented on optimade_client/query_provider.py
> +        ] = PROVIDER_DATABASE_GROUPINGS,
Instead of setting them here, could you set them to `None` and set them similarly to `database_limit` below?

2022-09-19 12:56 UTC, unkcpz commented on optimade_client/default_parameters.py
> +# it but has issue to serve the data.
Updated.

2022-09-19 12:57 UTC, unkcpz commented on optimade_client/query_provider.py
> +        ] = PROVIDER_DATABASE_GROUPINGS,
True, that's better. changed.

2022-09-19 13:22 UTC, CasperWA requested changes

2022-09-19 13:22 UTC, CasperWA commented on optimade_client/default_parameters.py
> +# Otherwise put in DISABLE_PROVIDERS means the client need to be supported but can't because of issues.
```suggestion
"""Default initialization parameters

The lists are set, based on the status of providers from
https://www.optimade.org/providers-dashboard/.

If the provider has no available databases, it should be put into the SKIP_PROVIDERS list,
meaning it will not be supported.
Providers in the DISABLE_PROVIDERS list are ones the client should support,
but cannot because of one issue or another.
"""
```

2022-09-19 13:22 UTC, CasperWA commented on optimade_client/query_provider.py
> +from typing import Union, Tuple, List, Dict
```suggestion
from typing import Union, Tuple, List, Dict, Optional
```

2022-09-19 13:22 UTC, CasperWA commented on optimade_client/query_provider.py
> +        ] = None,
```suggestion
        database_limit: Optional[int] = None,
        width_ratio: Optional[Union[Tuple[int, int], List[int]]] = None,
        width_space: Optional[int] = None,
        disable_providers: Optional[List[str]] = None,
        skip_providers: Optional[List[str]] = None,
        skip_databases: Optional[List[str]] = None,
        provider_database_groupings: Optional[
            Dict[str, Dict[str, List[str]]]
        ] = None,
```

2022-09-19 13:41 UTC, CasperWA commented
Because I can't run `black` through my suggested changes, you need to just run `pre-commit run --all-files` locally, commit any changes, and then push them - then the `pre-commit` CI test should succeed.

2022-09-19 14:06 UTC, unkcpz commented
Ah really sorry about this @CasperWA 😅. I just found it and first time using the 'batch commit' functionality. Didn't notice the CI fail. 
Should be fine now.

2022-09-19 20:55 UTC, CasperWA commented
> Ah really sorry about this @CasperWA 😅. I just found it and first time using the 'batch commit' functionality. Didn't notice the CI fail. Should be fine now.

Batch commit is great! It just doesn't run the pre-commit tools 😅

2022-09-19 20:56 UTC, CasperWA approved these changes

2022-09-19 20:56 UTC, merged