Test with Python 3.10
CasperWA/voila-optimade-client pull request #474
Opened 2022-12-12 15:33 UTC by danielhollas

We're trying to use Python 3.10 in AiiDAlab and need to test if all dependencies support it.

`optimade-client` currently declares support only up to Python 3.9 . Is there any known reason that it doesn't support higher versions?

cc @unkcpz

2022-12-12 17:10 UTC, danielhollas commented
@unkcpz or @CasperWA can you approve the workflows to run on this PR? Thanks!

2022-12-12 17:14 UTC, unkcpz commented
Hi @danielhollas, I don't have permission to do that. It has to be @CasperWA. Maybe @CasperWA can give me write permission for this repo?

2022-12-13 08:15 UTC, CasperWA requested changes

2022-12-13 08:15 UTC, CasperWA commented on .github/workflows/ci_tests.yml
> +        python-version: ["3.7", "3.8", "3.10"]
```suggestion
        python-version: ["3.7", "3.8", "3.9", "3.10"]
```
Why remove testing Python 3.9??

2022-12-13 08:18 UTC, CasperWA commented
> We're trying to use Python 3.10 in AiiDAlab and need to test if all dependencies support it.
> 
> `optimade-client` currently declares support only up to Python 3.9 . Is there any known reason that it doesn't support higher versions?

It's an older package. Python 3.10 is new. It's just the way of things.
Simply because support for higher/newer versions are not explicitly declared doesn't mean it shouldn't work.
It's easy to test locally by simply installing the package under a newer Python version and testing it out - no need to force the explicit metadata declaration simultaneously - just saying.

2022-12-13 08:30 UTC, CasperWA commented
Also. If you want to have explicit support for Python 3.10, please update `setup.py` appropriately in this PR as well.

2022-12-13 11:28 UTC, danielhollas commented
@CasperWA thank you for the info. 

I am putting this as a Draft until we can manually verify that everything works with Python 3.10. 
I don't personally use this package so I am not a good person for that. 

@unkcpz I will link this PR in the Python 3.10 issue as a TODO item.

2023-08-29 10:48 UTC, CasperWA commented
This repository has been extended to support Python 3.9-11, removing support for Python 3.7-8.

2023-08-29 10:48 UTC, closed without merging